#!/bin/bash

# TabBar 简单图标创建脚本
# 创建最小化的单色 PNG 图标

cat << 'EOF'
正在创建 TabBar 图标占位符...

注意：此脚本创建的是非常简单的占位图标。
建议从以下渠道获取更精美的图标：
1. Iconfont (https://www.iconfont.cn/)
2. IconPark (https://iconpark.oceanengine.com/)
3. Flaticon (https://www.flaticon.com/)

详细说明请查看 README.md 和 UPLOAD_GUIDE.md
EOF

cd "$(dirname "$0")"

# 创建一个简单的81x81灰色方形图标的base64
# 这是一个透明的PNG，中心有一个简单的灰色圆圈
GRAY_CIRCLE='iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAd5JREFUeJzt3CFuFEEYhtFvNmQBCHaMgzUgcFyxBQIHF1cgEDhOwAkQ2ABCAwaDoOveZjKZmf+9J6ZNM/1l0tU/TdM0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4P/ULPnYTfj/vfj6u8dP7d937fPz8vHv/9OXL7v3dw8Pu/frurnt/dXnZvX/+9at7L+k1/xif3r/v3t/c3HTvb29vu/fyj2F9XwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Ef6Be+vr3fvZ+v17v1sverev62vd+9Xq9Xu/Xy5XO/ej9Zy0b2/uLjo3qenp937o0ePuvfJyUn3Xv4xHD8+7t7PP4b1fQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP6hfkHXdft/vS7v5+v17n2xWOzej1Z/v7rb373v/TGsrwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgH+oX9H6+3r2fLZe79+v1evd+tlzu3q/W6+79bLnc/X+9W912788eP+7en56edO8lj4+Pu/fyj2F9XwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPBP/QZzJXCMz0sGjgAAAABJRU5ErkJggg=='

BROWN_CIRCLE='iVBORw0KGgoAAAANSUhEUgAAAFEAAABRCAYAAACqj0o2AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEwAACxMBAJqcGAAAAeFJREFUeJzt3TFuFEEYhdFvNiQrQCCQOCQOiJAdEBAQEhASEhASsgcC1oBAEBAQEBAQEBAQEBAQ8Numb2aqqv/vPWna1p9+qer+6ZqmCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADg/6pf8L6b8Pd59/Nxg5/ev+3e5+Pn5937py9fdu/vHh5279d3d937q8vL7v3zr1/de0lv+Mf49P59937j5qZ7f3t7270Xfwzq+wIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4j/QL3l1f797P1uvd+9l6vXt/W1/v3q9Wq937+XK13r0freWie39xcdG9T09Pu/dHjx517+Ufw/HjR937+cewvi8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/yL9gq7r9v96Xd7P1+vd+2Kx2L0frf5+dbf/e9/7Y1hfFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP9Qv6D38/XufWO53L1fr9e797Plcvd+tV7v3s+Wy93/17vVbff+7PHj7v3pyUn3XvL46Kh7L/8Y1vcFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/1O/AQcScJEPSbiNAAAAAElFTkSuQmCC'

# 解码并创建图标文件
echo "$GRAY_CIRCLE" | base64 -d > home.png
echo "$GRAY_CIRCLE" | base64 -d > order.png
echo "$GRAY_CIRCLE" | base64 -d > cart.png
echo "$GRAY_CIRCLE" | base64 -d > user.png

echo "$BROWN_CIRCLE" | base64 -d > home-active.png
echo "$BROWN_CIRCLE" | base64 -d > order-active.png
echo "$BROWN_CIRCLE" | base64 -d > cart-active.png
echo "$BROWN_CIRCLE" | base64 -d > user-active.png

echo ""
echo "✓ 已创建 8 个占位图标文件"
echo "✓ 默认状态: home.png, order.png, cart.png, user.png"
echo "✓ 选中状态: home-active.png, order-active.png, cart-active.png, user-active.png"
echo ""
echo "建议替换为更精美的图标！详见 README.md"
